#!/usr/bin/env bash

# This script is idempotent in the sense that running it more
# than once will not change the state beyond the initial application

set -euxo pipefail

CHAIN=$1
DOMAIN=$2
BRANCH=$3
COMMIT=$4
REVISION="ord-$BRANCH-$COMMIT"

touch ~/.hushlogin

sed -i -E 's/#?PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config

mkdir -p \
  /etc/systemd/system/peercoind.service.d \
  /etc/systemd/system/ord.service.d

printf "[Service]\nEnvironment=CHAIN=%s\n" $CHAIN \
  | tee /etc/systemd/system/peercoind.service.d/override.conf \
  > /etc/systemd/system/ord.service.d/override.conf

printf 'BRANCH=%s\n' $BRANCH >> /etc/environment \
  && printf 'COMMIT=%s\n' $COMMIT >> /etc/environment \
  && printf 'REVISION=%s\n' $REVISION >> /etc/environment

hostnamectl set-hostname $DOMAIN

apt-get install --yes \
  acl \
  clang \
  libsqlite3-dev\
  libssl-dev \
  pkg-config \
  ufw \
  vim

ufw default allow outgoing
ufw default deny incoming

ufw allow 8080
ufw allow http
ufw allow https
ufw allow ssh

case $CHAIN in
  main)
    ufw allow 9902
    ;;
  signet) # Peercoin doesn't have a signet
    ufw allow 38333
    ;;
  test)
    ufw allow 9904
    ;;
  *)
    echo "Unknown chain: $CHAIN"
    exit 1
    ;;
esac

ufw --force enable

if ! which peercoind; then
  ./bin/install-peercoin-core-linux
fi

peercoind --version

if [[ ! -e ~/.cargo/env ]]; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

source ~/.cargo/env

rustup update stable

cargo build --release
if [[ -f /usr/local/bin/ord ]]; then
  mv /usr/local/bin/ord /usr/local/bin/$REVISION.bak
fi
cp target/release/ord /usr/local/bin/ord

id --user peercoin || useradd --system peercoin
id --user ord || useradd --system ord

cp deploy/peercoind.service /etc/systemd/system/
mkdir -p /etc/peercoin
cp deploy/peercoin.conf /etc/peercoin/peercoin.conf
systemctl daemon-reload
systemctl enable peercoind
systemctl restart peercoind

case $CHAIN in
  main)
    COOKIE_FILE_DIR=/var/lib/peercoind
    ;;
  signet)
    COOKIE_FILE_DIR=/var/lib/peercoind/signet
    ;;
  test)
    COOKIE_FILE_DIR=/var/lib/peercoind/testnet3
    ;;
  *)
    echo "Unknown chain: $CHAIN"
    exit 1
    ;;
esac

while [[ ! -f $COOKIE_FILE_DIR/.cookie ]]; do
  echo "Waiting for peercoind…"
  sleep 1
done

setfacl -m ord:x /var/lib/peercoind
setfacl -m ord:x $COOKIE_FILE_DIR
setfacl -dm ord:r $COOKIE_FILE_DIR
setfacl -m ord:r $COOKIE_FILE_DIR/.cookie

journalctl --unit ord --vacuum-time 1s

cp deploy/ord.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable ord
systemctl restart ord

while ! curl --fail https://$DOMAIN/status; do
  echo "Waiting for ord at https://$DOMAIN/status…"
  sleep 1
done
